### ISSUE TITLE
404 on query 'tax data'

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#413]
go to: http://opendatanetwork-staging.herokuapp.com/

query 'tax data' and hit enter:

note: tries to forward the user to a URL w/ a 404

**Comment by ToshMeston** [comment]
I didn't know we were querying a dataset for the list datasets in autosuggest.  Can we just remove the "Business Tax Data" entry from it since it has evidently been deleted from the Santa Rosa portal (data.srcity.org)? @zang0 

https://federal.demo.socrata.com/dataset/ODN-Autocomplete-Datasets/xgvf-x2cr
Search for "tax data".  Find "Business Tax Data".

**Comment by ToshMeston** [comment]
@zang0 OK to just delete this dead dataset record from the ODN-Autocomplete-Datasets dataset?

**Comment by zang0** [comment]
sure

**Comment by ToshMeston** [comment]
@aaasen Lane can you kill the record.  I don't have a login.

**Comment by aaasen** [comment]
I updated the autocomplete datasets for publishers, categories, and datasets which should fix the problem. Changes are still propagating through the system but the issue should be resolved shortly.
