### ISSUE TITLE
weird results appearing for category searches

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#438]
go to: http://www.opendatanetwork.com/search?categories=finance&debug=true
note the query in the js console. now execute the cetera query:
http://api.us.socrata.com/api/catalog/v1?categories=finance

note: compare the UX results to the cetera results - they're totally different. 
![screen shot 2016-05-26 at 2 44 41 pm](https://cloud.githubusercontent.com/assets/1051776/15591197/6f9e1b1c-2350-11e6-86e6-8258dd97820b.png)
![screen shot 2016-05-26 at 2 44 32 pm](https://cloud.githubusercontent.com/assets/1051776/15591198/6fb061c8-2350-11e6-9569-8a4ef70ce2a5.png)
![screen shot 2016-05-26 at 2 44 24 pm](https://cloud.githubusercontent.com/assets/1051776/15591199/6fc54aca-2350-11e6-8c14-1a2611e0efa1.png)

**Comment by zang0** [comment]
note:

http://www.opendatanetwork.com/search?categories=finance
vs
http://opendatanetwork-staging.herokuapp.com/search?categories=finance

latter look good. @aaasen are we sure we cycled the caches correctly?

**Comment by ToshMeston** [comment]
I'm sure this is just old results in the prod cache.  We should just pop it.

**Comment by ToshMeston** [comment]
When I looked, the staging results were out of sync from the cetera results.  I've flushed the staging cache, now cetera, prod and staging are in sync.

**Comment by ToshMeston** [comment]
Currently, the cache is set to never expires items.  I am assuming this is OK.

**Comment by zang0** [comment]
_1 the results now look equally bad on prod and in staging - before, staging looked pretty good. Send the query we are using over to @rlvoyer so we can make sure we're using the right query from cetera and getting the expected results.

_2 i think 12 hours is more than enough time for the cache time to live - we still want fresh results from cetera as they tweak their results and new data sets come in. Can't remember why it was set so huge, maybe @aaasen knows.

**Comment by rlvoyer** [comment]
I suspect there are 2 reasons we are seeing some wonky results. 1) we are tagging a lot more than we used to be; w/ the increase in recall come lots of FPs and 2) we are allowing some datasets to have as many tags as the model thinks is likely; we are going to limit this, since at the moment, it seems like datasets w/ a lot of content (ie. large description or many, wordy column descriptions) end up getting lots of tags. Anyway, two immediate action items: 1) update the model to limit the number of predictions per dataset and for you guys 3) change the category query from a category facet query to a keyword search for the category string (ie. q=finance rather than categories=finance in the call to cetera). Our latest relevance measurements suggest that the latter will bring a significant improvement over the facet search. @ToshMeston let me know if this isn't clear.

**Comment by ToshMeston** [comment]
Changed code to append categories to the q= parameter and do not pass a "categories" parameter to cetera.  Changed cache TTL for all items to 12 hours.

The search results seem OK to me "Public Safety" shows results with "Public Safety" in the title generally.  Same with "Finance", etc.

Fixed.

**Comment by zang0** [comment]
looks good
