### ISSUE TITLE
make colors more extreme in maps

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#469]
see: http://opendatanetwork-staging-pr-467.herokuapp.com/region/0400000US53/Washington/population/annual_population_change/2013?

note: pop count should be more green but winding up yellow. lets tweaks such that colors are closer to the live site

**Comment by aaasen** [comment]
OK, fixed this. I realized that I was being dumb and that we can easily calculate the median and quartiles that we were using before using SOQL. Just takes a few requests.

Production:

http://www.opendatanetwork.com/region/310M200US42660/Seattle_Metro_Area_(WA)/population/population_change/2013?
<img width="1139" alt="screen shot 2016-07-22 at 9 48 37 pm" src="https://cloud.githubusercontent.com/assets/1320603/17075879/285625ae-5057-11e6-81a6-a11be5f17219.png">

New: 

http://opendatanetwork-staging-pr-467.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/population/annual_population_change/2013?
<img width="1139" alt="screen shot 2016-07-22 at 9 56 21 pm" src="https://cloud.githubusercontent.com/assets/1320603/17075880/2c8f68c4-5057-11e6-81a9-e00cecc4e8e0.png">

Only difference is that I added one more color to the scale so now it is 8 colors instead of 7. This makes the ticks line up properly.

Now, the only difference between what we have currently and prod is variable names.

**Comment by zang0** [comment]
Looks like the maps are totally broken now. The above links just go to a broken map.

**Comment by aaasen** [comment]
I can't reproduce this issue. Which browser are you using? What do you mean by broken?

**Comment by zang0** [comment]
still fails after full cache reset and browser bounce. chrome v=Version 51.0.2704.103 (64-bit), also fails on safari (Version 9.1.1 (11601.6.17))

Screen shots attached. Note: maps are blank w/ no data.

![Uploading Screen Shot 2016-07-30 at 7.38.37 AM.png…]()
<img width="1327" alt="screen shot 2016-07-30 at 7 38 24 am" src="https://cloud.githubusercontent.com/assets/1051776/17266299/200c78e4-5629-11e6-80c1-964aa612c818.png">

**Comment by zang0** [comment]
<img width="1103" alt="screen shot 2016-07-30 at 7 44 34 am" src="https://cloud.githubusercontent.com/assets/1051776/17266335/7f0a6f4a-5629-11e6-955a-bdb8c352066d.png">

**Comment by zang0** [comment]
closing this.
