### ISSUE TITLE
crime incident rate x axis wrong 

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#585]
compare values to x axis, scale is wrong

https://opendatanetwork-staging.herokuapp.com/entity/1600000US1714000-1600000US4159000-1600000US5363000/Chicago_IL-Portland_OR-Seattle_WA/crime.fbi_ucr.count?crime_type=Aggravated%20assault&year=2014&ref=compare-entity

**Comment by chrismetcalf** [comment]
@aaasen Shouldn't the chart react to the values I return from odn-backend? I need to scale them x 100k

**Comment by aaasen** [comment]
The change that you made will change the formatted values, but it will not change the underlying values. This is the API call that the chart is using: https://api.opendatanetwork.com/data/v1/values?app_token=cQovpGcdUT1CSzgYk0KPYdAI0&describe=true&format=google&variable=crime.fbi_ucr.rate&entity_id=1600000US1714000%2C1600000US4159000%2C1600000US5363000&year=2014

The backend really isn't set up to transform the data like this - we will need to add something to transform the underlying values instead of just formatting them.

**Comment by chrismetcalf** [comment]
I'll have to republish the dataset with per 100k rates then. Thanks!

**Comment by zang0** [comment]
Will regenerate dataset and should get about 10% more cities and years.

**Comment by chrismetcalf** [comment]
Fixed in https://github.com/socrata/odn-backend/pull/66, once that gets to production

**Comment by chrismetcalf** [comment]
Fixed (In staging) https://opendatanetwork-staging.herokuapp.com/entity/1600000US1150000/Washington_DC/crime.fbi_ucr.count?crime_type=Aggravated%20assault&year=2014
